/**:
  ros__parameters:
    onnx_path: "$(var model_path)/frnet_$(var sensor_model).onnx"
    trt_precision: fp16
    filter:
      class_probability_threshold: 0.05
      classes: ["drivable_surface"]
      output_format: ""
      ego_crop_box:
        reference_frame: base_link
        min_x: 0.0
        min_y: 0.0
        min_z: 0.0
        max_x: 0.0
        max_y: 0.0
        max_z: 0.0
